name: actions/karna
author: Aymeric Aveline
description: Action to deploy a lambda function with Karna
inputs:
  alias:
    description: "Function alias"
    required: true
  name:
    description: "Function name"
    required: true
runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.alias }}
    - ${{ inputs.name }}
branding:
  icon: "award"
  color: "green"
